"""
TLS for every ZTNA control-plane and resource service, backed by the
internal CA (common/ca_utils.py) added in this hardening revision -- see
docs/HARDENING.md.

Original design: one ad-hoc self-signed cert per service, generated by
shelling out to the `openssl` CLI, with an HTTP fallback if openssl wasn't
on PATH (which silently weakened the "encrypt everything" NIST SP 800-207
principle -- see docs/CHANGELOG.md for a bug this caused). Because
certificate generation now uses the `cryptography` library (already a
required dependency) instead of an external tool, that fallback is no
longer necessary -- every service can always get a valid, CA-signed cert
on a bare Python install, so `scheme()` now always returns "https".
"""
import os
import ssl

from common.config import CA_CERT_PATH
from common import ca_utils


def ensure_service_cert(service_name: str) -> tuple:
    """Return (key_path, cert_path) for `service_name`, issuing it from the
    internal CA if it doesn't exist yet. Idempotent."""
    return ca_utils.issue_cert(service_name)


def scheme() -> str:
    """The URL scheme services come up on. Kept for backward compatibility
    with agent/client_agent.py and tests/test_ztna.py, which call this
    instead of hardcoding a scheme -- see docs/CHANGELOG.md for the bug
    that motivated that pattern originally. Always "https" as of this
    revision (see module docstring)."""
    return "https"


def wrap_server_socket(httpd, service_name: str, require_client_cert: bool = False):
    """Wrap an http.server socket in TLS in-place, using a CA-issued cert
    for `service_name`. If `require_client_cert` is True, the server will
    refuse any TLS handshake that doesn't present a client certificate
    signed by the same internal CA -- this is the mTLS enforcement used by
    resources/docs_app.py and resources/finance_app.py so that only the
    Gateway (which has the one issued client cert) can complete a
    connection at all, independent of firewall/loopback binding.

    Returns True (kept as a bool for backward-compat call sites; TLS is
    now always available since cert generation no longer depends on an
    external tool)."""
    key_path, cert_path = ensure_service_cert(service_name)

    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(certfile=cert_path, keyfile=key_path)

    if require_client_cert:
        ctx.verify_mode = ssl.CERT_REQUIRED
        ctx.load_verify_locations(cafile=CA_CERT_PATH)

    httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)
    return True


def build_client_ssl_context(client_cert_name: str = None) -> ssl.SSLContext:
    """Build an SSLContext for OUTBOUND connections that trusts the
    internal CA (so server certs verify for real, no more verify=False)
    and, if `client_cert_name` is given, presents a client certificate
    issued for that name -- used by the Gateway when it proxies to
    docs-app/finance-app over mTLS."""
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    ctx.load_verify_locations(cafile=CA_CERT_PATH)
    if client_cert_name:
        key_path, cert_path = ensure_service_cert(client_cert_name)
        ctx.load_cert_chain(certfile=cert_path, keyfile=key_path)
    return ctx
